export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';

export const FETCH_RESULT_START = 'FETCH_RESULT_START';
export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAIL = 'FETCH_RESULT_FAIL';

export const INIT_TEST = 'INIT_TEST';
export const SUBMIT_TEST_START = 'SUBMIT_TEST_START';
export const SUBMIT_TEST_SUCCESS = 'SUBMIT_TEST_SUCCESS';
export const SUBMIT_TEST_FAIL = 'SUBMIT_TEST_FAIL';